name: buildpdf
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tex'
permissions:
  contents: write  # allow pushes
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: SMasonGarrisonCV.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: SMasonGarrisonCV.pdf
      - name: Commit SMasonGarrisonCV.pdf to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f SMasonGarrisonCV.pdf
          git commit -m "Update built CV PDF" || echo "No changes to commit"
          git push
